name: Build test of Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: imperial-police

jobs:
  push:
    name: Build test of Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build an image with a tag
        run: docker build -t test .
