name: Build test of Docker Image

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: imperial-police

jobs:
  image_build_test:
    name: Build test of Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build an image with a tag
        run: docker build -t test .
